### DISCUSSION TITLE
Different device plugin configuration per node?

### DISCUSSION THREAD

**Discussion by amir-bialek** [NVIDIA/k8s-device-plugin#777] [Q&A] [answered]
Hey, on our first step we deploy the helm-chart on 1 master and 1 worker, the worker had 1 gpu that we shared for all services with:
```
devicePlugin:
  config:
    name: time-slicing-config-all
    create: true
    default: "any"
    data:
      any: |-
        version: v1
        flags:
          migStrategy: none
        sharing:
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 15
```

We tested it for 1 month, working well.
Now we added another node to the cluster, the gpu is also expose and any pod we deploy on it can access it.
However the new node have 9 gpu's on it, so we do not want to use the time-slicing feature here.
Is there a way to configure the helmchart under the ``` devicePlugin.config: ``` to have a separate configuration per node?
