### ISSUE TITLE
Is it possible to turn of timeslising for one node group?

### ISSUE THREAD

**Issue by oleksiytsyban** [NVIDIA/k8s-device-plugin#1022]
It is possible to configure different time slicing values with  `nvidia.com/device-plugin.config` label (the example is from helm values file):

```
config:
  # Set of named configs to build an integrated ConfigMap from
  map: 
     label1: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
              - name: nvidia.com/gpu
                replicas: 2
     label2: |-
          <no timeslising here, i.e. replicas:1>
  # Default config name within the ConfigMap
  default: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
              - name: nvidia.com/gpu
                replicas: 4
```
Is it possible to turn off time slicing for one particular label, label2 above? `replicas:1` is not a correct value for the helm chart.

**Comment by klueska** [comment]
Yes, please refer to:
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#applying-multiple-node-specific-configurations

You would change what you have above to:
```
 label1: |-
      version: v1
      sharing:
        timeSlicing:
          resources:
          - name: nvidia.com/gpu
            replicas: 2
label2: |-
      version: v1
      <no timeslising here, i.e. replicas:1>
  # Default config name within the ConfigMap
  default: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
              - name: nvidia.com/gpu
                replicas: 4
```
And then apply the appropriate config to the the nodes you care about with:
```
kubectl label node -l label1 nvidia.com/device-plugin.config=label1
kubectl label node -l label2 nvidia.com/device-plugin.config=label2
```

**Comment by oleksiytsyban** [comment]
Thank you. The config below works just fine.
```
spec:
  values:
    config:
      fallbackStrategies: ["named" , "single"]
      map:
        default: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
              - name: nvidia.com/gpu
                replicas: 3
        no-slicing: |-
          version: v1
```
