### ISSUE TITLE
CrashLoopBackOff message wen running GPU Jobs example and others

### ISSUE THREAD

**Issue by JungukCho** [NVIDIA/k8s-device-plugin#106]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
I installed all packages and daemonset referring Enabling GPU Support in Kubernetes
from "https://github.com/NVIDIA/k8s-device-plugin".
However,  I could not run "Running GPU Jobs" example (ie., cuda-container) or others.
They showed "CrashLoopBackOff" messages.
However some examples (e.g., tensorflow) which uses GPU worked.

### 2. Steps to reproduce the issue
$ cat cuda.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cuda-container
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:9.0-devel
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 2 GPUs
```

$ cat tensorrt.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tensorrt
spec:
  containers:
    - name: tensorrt
      image: "nvcr.io/nvidia/tensorrt:18.08-py2"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
```

$ kubectl apply -f cuda.yaml or kubectl apply -f tensorrt.yaml

NAME             READY   STATUS             RESTARTS   AGE   IP            
cuda-container   0/1     CrashLoopBackOff   1          9s    10.244.1.38 

NAME       READY   STATUS             RESTARTS   AGE   IP           
tensorrt   0/1     CrashLoopBackOff   3          62s   10.244.1.37  

However, if I ran some examples, they worked.
1. Tensorflow
$ cat  tf.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tf-gpu
spec:
  containers:
  - name: gpu
    image: tensorflow/tensorflow:1.9.0-gpu
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1024Mi
        # ^ Set memory in case default limits are set low
        nvidia.com/gpu: 1 # requesting 1 GPUs
        # ^ For Legacy Accelerators mode this key must be renamed
        #   'alpha.kubernetes.io/nvidia-gpu'
  tolerations:
  # This toleration will allow the gpu hook to run anywhere
  #   By default this is permissive in case you have tainted your GPU nodes.
  - operator: "Exists"
  # ^ If you have a specific taint to target, comment out the above and modify
  #   the example below
### Example tolerations
# - key: "dedicated"
#   operator: "Equal"
#   value: "gpu"
#   effect: "NoExecute"
```
2. cat  digits.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: digits-container
      image: nvidia/digits:6.0
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
```

Both ran correctly and showed below message 
$ kubectl exec gpu-pod nvidia-smi
Mon Apr  1 23:18:10 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   43C    P0    24W /  75W |    129MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
nvidia-smi 
Mon Apr  1 16:07:49 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   34C    P8     7W /  75W |      0MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 cat /etc/docker/daemon.json 
{
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "default-runtime": "nvidia",
    "exec-opts": ["native.cgroupdriver=systemd"],
    "log-driver": "json-file",
    "log-opts": {
      "max-size": "100m"
    },
    "storage-driver": "overlay2",
    "storage-opts": [
      "overlay2.override_kernel_check=true"
    ]
}
 - [ ] The k8s-device-plugin container logs
 kubectl logs nvidia-device-plugin-daemonset-1.12-zkg5z  -n kube-system
2019/04/01 17:45:23 Loading NVML
2019/04/01 17:45:23 Fetching devices.
2019/04/01 17:45:23 Starting FS watcher.
2019/04/01 17:45:23 Starting OS watcher.
2019/04/01 17:45:23 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2019/04/01 17:45:23 Registered device plugin with Kubelet

 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
Apr 01 16:07:33 machine1 kubelet[3438]: W0401 16:07:33.386135    3438 container.go:523] Failed to update stats for container "/libcontainer_31425_systemd_test_default.slice": open /sys/fs/cgroup/cpu,cpuacct/libcontainer_31425_systemd_test_default.slice/cpuacct.usage: no such file or directory, continuing to push stats
Apr 01 16:07:33 machine1 kubelet[3438]: W0401 16:07:33.393734    3438 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_31425_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory
Apr 01 16:07:33 machine1 kubelet[3438]: W0401 16:07:33.393813    3438 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_31425_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_31425_systemd_test_default.slice: no such file or directory
Apr 01 16:07:34 machine1 kubelet[3438]: E0401 16:07:34.343189    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"
Apr 01 16:07:35 machine1 kubelet[3438]: E0401 16:07:35.259592    3438 cadvisor_stats_provider.go:432] Partial failure issuing cadvisor.ContainerInfoV2: partial failures: ["/libcontainer_31425_systemd_test_default.slice": RecentStats: unable to find data in memory cache]
Apr 01 16:07:45 machine1 kubelet[3438]: E0401 16:07:45.315887    3438 cadvisor_stats_provider.go:432] Partial failure issuing cadvisor.ContainerInfoV2: partial failures: ["/libcontainer_31425_systemd_test_default.slice": RecentStats: unable to find data in memory cache]
Apr 01 16:07:47 machine1 kubelet[3438]: E0401 16:07:47.703663    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"
Apr 01 16:08:00 machine1 kubelet[3438]: E0401 16:08:00.703525    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"
Apr 01 16:08:11 machine1 kubelet[3438]: E0401 16:08:11.703608    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"
Apr 01 16:08:22 machine1 kubelet[3438]: E0401 16:08:22.703656    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"
Apr 01 16:08:36 machine1 kubelet[3438]: E0401 16:08:36.703596    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"
Apr 01 16:08:50 machine1 kubelet[3438]: E0401 16:08:50.703597    3438 pod_workers.go:190] Error syncing pod b8a19682-54d2-11e9-b892-ac162d85318c ("cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"), skipping: failed to "StartContainer" for "cuda-container" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=cuda-container pod=cuda-container_default(b8a19682-54d2-11e9-b892-ac162d85318c)"

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
In worker node which has one GPU
Docker version : 18.09.4
NVIDIA Docker: 2.0.3

 - [ ] Kernel version from `uname -a`
3.10.0-693.21.1.el7.x86_64 #1 SMP 

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
rpm -qa '*nvidia*'
libnvidia-container-tools-1.0.0-0.1.rc.1.x86_64
nvidia-kmod-390.46-2.el7.x86_64
nvidia-container-runtime-2.0.0-1.docker18.09.4.x86_64
xorg-x11-drv-nvidia-libs-390.46-1.el7.x86_64
xorg-x11-drv-nvidia-390.46-1.el7.x86_64
nvidia-docker2-2.0.3-1.docker18.09.4.ce.noarch
xorg-x11-drv-nvidia-devel-390.46-1.el7.x86_64
xorg-x11-drv-nvidia-diagnostic-390.46-1.el7.x86_64
nvidia-container-runtime-hook-1.4.0-2.x86_64
xorg-x11-drv-nvidia-gl-390.46-1.el7.x86_64
libnvidia-container1-1.0.0-0.1.rc.1.x86_64
nvidia-diag-driver-local-repo-rhel7-390.46-1.0-1.x86_64

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.0
