### ISSUE TITLE
Shared GPU access of MPS type doesn't work.

### ISSUE THREAD

**Issue by allyrr** [NVIDIA/k8s-device-plugin#1105]
I faced with the below error when trying to deploy `nvidia-device-plagin` with MPS enabled.

**mps-control-daemon-ctr**  container of **nvdp-g4dn-xlarge-4gb-gpu-nvidia-device-plugin-mps-control** pod throws:
```
# error:
I1220 11:03:48.250278 99 main.go:197] Retrieving MPS daemons.
I1220 11:03:48.293356 99 daemon.go:97] "Staring MPS daemon" resource="nvidia.com/gpu"
I1220 11:03:48.293406 99 daemon.go:156] "SELinux enabled, setting context" path="/mps/nvidia.com/gpu/pipe" context="system_u:object_r:container_file_t:s0"
E1220 11:03:48.293764 99 main.go:213] Failed to start MPS daemon: error setting SELinux context: lsetxattr /mps/nvidia.com/gpu/pipe: permission denied
I1220 11:03:48.293787 99 main.go:132] Failed to start one or more MPS deamons. Retrying in 30s...
W1220 11:04:18.319988 99 main.go:228] Failed to remove .ready file: remove /mps/.ready: no such file or directory
I1220 11:04:18.320030 99 main.go:230] Stopping MPS daemons.
E1220 11:04:18.320215 99 main.go:84] error stopping plugins from previous run: error sending quit message: failed to start NVIDIA MPS command: exec: "nvidia-cuda-mps-control": executable file not found in $PATH
```

the helm chart value.yaml:
```
config:
  map:
    default: |-
      version: v1
      sharing:
        mps:
          resources:
            - name: nvidia.com/gpu
              replicas: 4
gfd:
  enabled: true
tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: karpenter-g4dn-xlarge-4gb-gpu
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
nfd:
  worker:
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: karpenter-g4dn-xlarge-4gb-gpu
      - key: CriticalAddonsOnly
        operator: Exists
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
```

EKS version: 1.30
nvdp version: 0.17

**Comment by chipzoller** [comment]
I have no problems taking your same Helm values and deploying the same version of the device plugin on an EKS 1.30 cluster. Logs from the MPS control daemon shown below. Ignore the namespace name; the device plugin was not deployed via the operator. Instance type used for testing was one g4dn.xlarge with a T4 GPU.

<details><summary>Log details</summary>
<p>

```log
$ stern -n nvidia-gpu-operator nvdp-nvidia-device-plugin-mps-control-daemon
+ nvdp-nvidia-device-plugin-mps-control-daemon-2js7n › mps-control-daemon-init
+ nvdp-nvidia-device-plugin-mps-control-daemon-2js7n › mps-control-daemon-sidecar
+ nvdp-nvidia-device-plugin-mps-control-daemon-2js7n › mps-control-daemon-mounts
+ nvdp-nvidia-device-plugin-mps-control-daemon-2js7n › mps-control-daemon-ctr
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.069030      44 main.go:81] "NVIDIA MPS Control Daemon" version=<
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       d475b2cf
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       commit: d475b2cfcf12b983a4975d4fc59d91af432cf28e
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr  >
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.069268      44 main.go:110] Starting OS watcher.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar W1220 13:30:23.897446      33 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-mounts I1220 13:30:22.622543       7 main.go:81] "NVIDIA MPS Control Daemon" version=<
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init W1220 13:30:22.896492      21 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-mounts    d475b2cf
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-mounts    commit: d475b2cfcf12b983a4975d4fc59d91af432cf28e
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-mounts  >
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init I1220 13:30:22.897341      21 main.go:246] Waiting for change to 'nvidia.com/device-plugin.config' label
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init I1220 13:30:22.906841      21 main.go:248] Label change detected: nvidia.com/device-plugin.config=
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init I1220 13:30:22.906932      21 main.go:368] No value set and no default set. Attempting fallback strategies: [named single]
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init I1220 13:30:22.906950      21 main.go:372] Attempting to find config named: default
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init I1220 13:30:22.906956      21 main.go:304] Updating to config: default
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-init I1220 13:30:22.907022      21 main.go:319] Successfully updated to config: default
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.898243      33 main.go:246] Waiting for change to 'nvidia.com/device-plugin.config' label
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.908330      33 main.go:248] Label change detected: nvidia.com/device-plugin.config=
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.908413      33 main.go:368] No value set and no default set. Attempting fallback strategies: [named single]
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.908426      33 main.go:372] Attempting to find config named: default
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.908432      33 main.go:304] Updating to config: default
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.908498      33 main.go:312] Already configured. Skipping update...
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-sidecar I1220 13:30:23.908506      33 main.go:246] Waiting for change to 'nvidia.com/device-plugin.config' label
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.069530      44 main.go:124] Starting Daemons.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.069578      44 main.go:167] Loading configuration.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.069950      44 main.go:182] Updating config with default resource matching patterns.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.070006      44 main.go:193] 
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr Running with config:
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   "version": "v1",
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   "flags": {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "migStrategy": "none",
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "failOnInitError": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "gdsEnabled": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "mofedEnabled": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "useNodeFeatureAPI": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "deviceDiscoveryStrategy": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "plugin": {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "passDeviceSpecs": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "deviceListStrategy": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "deviceIDStrategy": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "cdiAnnotationPrefix": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "nvidiaCTKPath": null,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "containerDriverRoot": null
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     }
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   },
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   "resources": {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "gpus": [
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr         "pattern": "*",
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr         "name": "nvidia.com/gpu"
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       }
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     ]
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   },
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   "sharing": {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "timeSlicing": {},
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     "mps": {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "failRequestsGreaterThanOne": true,
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       "resources": [
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr         {
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr           "name": "nvidia.com/gpu",
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr           "devices": "all",
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr           "replicas": 4
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr         }
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr       ]
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr     }
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   },
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr   "imex": {}
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr }
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.070020      44 main.go:197] Retrieving MPS daemons.
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.106403      44 daemon.go:97] "Staring MPS daemon" resource="nvidia.com/gpu"
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.106471      44 daemon.go:150] "SELinux disabled, not updating context" path="/mps/nvidia.com/gpu/pipe"
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr I1220 13:30:24.110416      44 daemon.go:139] "Starting log tailer" resource="nvidia.com/gpu"
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.107 Control    59] Starting control daemon using socket /mps/nvidia.com/gpu/pipe/control
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.107 Control    59] To connect CUDA applications to this daemon, set env CUDA_MPS_PIPE_DIRECTORY=/mps/nvidia.com/gpu/pipe
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.108 Control    59] Accepting connection...
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.108 Control    59] NEW UI
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.109 Control    59] Cmd:set_default_device_pinned_mem_limit 0 3840M
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.109 Control    59] UI closed
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.110 Control    59] Accepting connection...
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.110 Control    59] NEW UI
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.110 Control    59] Cmd:set_default_active_thread_percentage 25
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.110 Control    59] 25.0
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:24.110 Control    59] UI closed
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:47.218 Control    59] Accepting connection...
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:47.218 Control    59] NEW UI
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:47.219 Control    59] Cmd:get_default_active_thread_percentage
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:47.219 Control    59] 25.0
nvdp-nvidia-device-plugin-mps-control-daemon-2js7n mps-control-daemon-ctr [2024-12-20 13:30:47.219 Control    59] UI closed
```

</p>
</details> 

Node labels as follows.

<details><summary>Node label details</summary>
<p>

```yaml
beta.kubernetes.io/arch: amd64
beta.kubernetes.io/instance-type: g4dn.xlarge
beta.kubernetes.io/os: linux
eks.amazonaws.com/capacityType: ON_DEMAND
eks.amazonaws.com/nodegroup: brave_kalam
eks.amazonaws.com/nodegroup-image: ami-0a9ed5c9854bb8a0c
failure-domain.beta.kubernetes.io/region: us-east-1
failure-domain.beta.kubernetes.io/zone: us-east-1c
feature.node.kubernetes.io/cpu-cpuid.ADX: "true"
feature.node.kubernetes.io/cpu-cpuid.AESNI: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX512BW: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX512CD: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX512DQ: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX512F: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX512VL: "true"
feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: "true"
feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: "true"
feature.node.kubernetes.io/cpu-cpuid.FMA3: "true"
feature.node.kubernetes.io/cpu-cpuid.FXSR: "true"
feature.node.kubernetes.io/cpu-cpuid.FXSROPT: "true"
feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "true"
feature.node.kubernetes.io/cpu-cpuid.LAHF: "true"
feature.node.kubernetes.io/cpu-cpuid.MOVBE: "true"
feature.node.kubernetes.io/cpu-cpuid.MPX: "true"
feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: "true"
feature.node.kubernetes.io/cpu-cpuid.SYSCALL: "true"
feature.node.kubernetes.io/cpu-cpuid.SYSEE: "true"
feature.node.kubernetes.io/cpu-cpuid.X87: "true"
feature.node.kubernetes.io/cpu-cpuid.XGETBV1: "true"
feature.node.kubernetes.io/cpu-cpuid.XSAVE: "true"
feature.node.kubernetes.io/cpu-cpuid.XSAVEC: "true"
feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: "true"
feature.node.kubernetes.io/cpu-cpuid.XSAVES: "true"
feature.node.kubernetes.io/cpu-hardware_multithreading: "true"
feature.node.kubernetes.io/cpu-model.family: "6"
feature.node.kubernetes.io/cpu-model.id: "85"
feature.node.kubernetes.io/cpu-model.vendor_id: Intel
feature.node.kubernetes.io/kernel-config.NO_HZ: "true"
feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE: "true"
feature.node.kubernetes.io/kernel-version.full: 5.10.228-219.884.amzn2.x86_64
feature.node.kubernetes.io/kernel-version.major: "5"
feature.node.kubernetes.io/kernel-version.minor: "10"
feature.node.kubernetes.io/kernel-version.revision: "228"
feature.node.kubernetes.io/pci-10de.present: "true"
feature.node.kubernetes.io/pci-1d0f.present: "true"
feature.node.kubernetes.io/storage-nonrotationaldisk: "true"
feature.node.kubernetes.io/system-os_release.ID: amzn
feature.node.kubernetes.io/system-os_release.VERSION_ID: "2"
feature.node.kubernetes.io/system-os_release.VERSION_ID.major: "2"
k8s.io/cloud-provider-aws: 78a84c7549c85f75989a9f24e5266378
kubernetes.io/arch: amd64
kubernetes.io/hostname: ip-10-0-189-158.ec2.internal
kubernetes.io/os: linux
node.kubernetes.io/instance-type: g4dn.xlarge
nvidia.com/cuda.driver-version.full: 550.127.08
nvidia.com/cuda.driver-version.major: "550"
nvidia.com/cuda.driver-version.minor: "127"
nvidia.com/cuda.driver-version.revision: "08"
nvidia.com/cuda.driver.major: "550"
nvidia.com/cuda.driver.minor: "127"
nvidia.com/cuda.driver.rev: "08"
nvidia.com/cuda.runtime-version.full: "12.4"
nvidia.com/cuda.runtime-version.major: "12"
nvidia.com/cuda.runtime-version.minor: "4"
nvidia.com/cuda.runtime.major: "12"
nvidia.com/cuda.runtime.minor: "4"
nvidia.com/gfd.timestamp: "1734701388"
nvidia.com/gpu.compute.major: "7"
nvidia.com/gpu.compute.minor: "5"
nvidia.com/gpu.count: "1"
nvidia.com/gpu.family: turing
nvidia.com/gpu.machine: g4dn.xlarge
nvidia.com/gpu.memory: "15360"
nvidia.com/gpu.mode: compute
nvidia.com/gpu.product: Tesla-T4-SHARED
nvidia.com/gpu.replicas: "4"
nvidia.com/gpu.sharing-strategy: mps
nvidia.com/mig.capable: "false"
nvidia.com/mps.capable: "true"
nvidia.com/vgpu.present: "false"
topology.ebs.csi.aws.com/zone: us-east-1c
topology.k8s.aws/zone-id: use1-az6
topology.kubernetes.io/region: us-east-1
topology.kubernetes.io/zone: us-east-1c
```

</p>
</details>
