### ISSUE TITLE
Selecting MPS nodes to allow mixed strategy

### ISSUE THREAD

**Issue by santurini** [NVIDIA/k8s-device-plugin#1150]
I am running MPS in a kubernetes cluster with 3 nodes of 8 gpus each.
I am having troubles with OOM pods and wanted to know if there is a way to specify which GPUS (or even nodes) should have MPS enabled and which not, such that in the manifest it can be specified if the pod should use an entire GPU or only a fraction/replica

**Comment by chipzoller** [comment]
MPS has to be enabled on, at most granular, a per-node basis. It cannot be enabled on a per-GPU basis. If you set the device plugin up such that it uses `nvidia.com/gpu.shared` to advertise GPUs shared with MPS then you can specify in your resource manifests whether to use an exclusive GPU (`nvidia.com/gpu`) or shared GPU (`nvidia.com/gpu.shared`).

**Comment by santurini** [comment]
@chipzoller How can I tell the plugin on which nodes to deploy mps?

**Comment by chipzoller** [comment]
See the README section entitled "Shared Access to GPUs" for details. You will label the nodes with the name of the MPS config you wish to take effect.

**Comment by santurini** [comment]
So for example if on a specific node `nodeX` I want to have full gpus I can create a new ConfigMap `full-gpus` with replicas set to the number of gpus on the node, and then set `kubectl label nodes nodeX –-overwrite nvidia.com/device-plugin.config=full-gpus`.
Correct?

**Comment by chipzoller** [comment]
No, you don't need a config at all on nodes where you want exclusive GPU access.

**Comment by santurini** [comment]
Thats my point, when deploying the nvdp I have no way to specify the nodes on which i want to deploy it. It just gets deployed on all nodes. What I would like instead is to keep one node with exclusive GPU access and one node with replicas instead. From the README I don't get how can I achieve that.

**Comment by chipzoller** [comment]
I'm not understanding the confusion here. You create a named config which specifies the sharing configuration. Device plugin runs on all nodes with at least one GPU. You label only the node where you want that sharing config to be applied. All other nodes continue to use exclusive GPU access.

**Comment by santurini** [comment]
I don't get how to do this, like practically how can I do that, what do I have to change in my nvdp deploy.

> You label only the node where you want that sharing config to be applied.

**Comment by santurini** [comment]
Ok at the moment my nodes have a bunch of labels given by the gpu-operator and the device plugin. How should I label the node with exclusive access and how the node with shared access?

**Comment by chipzoller** [comment]
Assign the label manually to whichever nodes you want? Launch a Job that runs a similar `kubectl label node` command? Use an operator? All sorts of ways.

**Comment by santurini** [comment]
No, I mean which label should I use, in the documentation I don't find nothing related.

**Comment by chipzoller** [comment]
`nvidia.com/device-plugin.config`

**Comment by santurini** [comment]
None of my nodes has this label but still all of them have mps. 
Its more like I have to "remove" MPS from a specific node in the cluster.

**Comment by chipzoller** [comment]
You need to use a named config so the default is not MPS.

https://github.com/NVIDIA/k8s-device-plugin/blob/main/deployments%2Fhelm%2Fnvidia-device-plugin%2Fvalues.yaml#L1-L19

**Comment by marinoborges** [comment]
I think the question is more how to prevent MPS DaemonSet pods from running on a GPU node. I understand that it would require tweaking with MPS DaemonSet tolerations in the helm template file so nvidia plugin DaemonSet has different tolerations than MPS DaemonSet, which currently are the same.

In my case I'd like to have an option in the Helm values file to prevent MPS DaemonSet from being created while still having the nvidia plugin DaemonSet deployed as in versions before 0.15. Would that be ok?

**Comment by santurini** [comment]
@chipzoller I do use a custom configmap, and I can see it is applied by the number of available replicas, but still I don't have the node label you provided me.

This is how I deploy MPS on the cluster:
```bash
# deploy GPU Operator without device plugin
helm install \
      -n gpu-operator \
      --generate-name \
      --create-namespace \
      --set devicePlugin.enabled=false \
      --set gfd.enabled=false \
      nvidia/gpu-operator

# create nvdp namespace
kubectl create ns nvidia-device-plugin

# create MPS configmap
cat << EOF > dp-mps-config.yaml
version: v1
flags:
  migStrategy: "none"
  failOnInitError: true
  nvidiaDriverRoot: "/"
  plugin:
    passDeviceSpecs: false
    deviceListStrategy:
    - envvar
    deviceIDStrategy: uuid
sharing:
  mps:
    renameByDefault: false
    resources:
    - name: nvidia.com/gpu
      replicas: 2
EOF

kubectl create cm -n nvidia-device-plugin nvidia-plugin-configs \
    --from-file=config=dp-mps-config.yaml


# deploy nvdp with custom MPS configmap
helm upgrade nvdp -i nvdp/nvidia-device-plugin \
    --namespace nvidia-device-plugin \
    --create-namespace \
    --set runtimeClassName=nvidia \
    --set config.name=nvidia-plugin-configs \
    --set nvidiaDriverRoot=/ \
    --set gfd.enabled=true
```

And this custom configmap applies to all the nodes in the cluster, how can I re-deploy MPS to apply it only on a specific "node1" for instance?

**Comment by santurini** [comment]
Don't know if it can work by just setting this:
`nodeSelector: {}`

**Comment by chipzoller** [comment]
@santurini, as I tried to point out, the problem is you're using and applying _one configuration across all nodes_ and not separate configurations. The link I provided to the Helm chart values makes it clear how to do this but here is a tutorial. I'll pick an EKS cluster but it doesn't matter.

I've built a cluster having two nodes each with a T4 GPU. You can see these nodes below.

```sh
$ kubectl get nodes -o yaml | yq '.items[] | select(.status.allocatable| keys | .[] | select(test("^nvidia.com"))) | .metadata.name'
ip-10-0-141-2.ec2.internal
ip-10-0-78-52.ec2.internal
```

I'll now deploy the GPU operator with everything needed to bootstrap this cluster including a configuration file with multiple, different configurations.

```yaml
# These values validated on v24.6.1 of the NVIDIA GPU Operator.
driver:
  enabled: false
toolkit:
  enabled: true
cdi:
  enabled: true
  default: true
nfd:
  enabled: true
gfd:
  enabled: true
migManager:
  enabled: false
devicePlugin:
  enabled: true
  config:
    name: device-plugin-config
    create: true
    default: default
    data:
      default: |-
        version: v1
        flags:
          migStrategy: none
          failOnInitError: true
      test-sharing: |-
        version: v1
        sharing:
          timeSlicing:
            renameByDefault: true
            failRequestsGreaterThanOne: true
            resources:
            - name: nvidia.com/gpu
              replicas: 4
      test-mps: |-
        version: v1
        sharing:
          mps:
            renameByDefault: true
            resources:
            - name: nvidia.com/gpu
              replicas: 2
dcgmExporter:
  enabled: true
```

The configuration named `default` will apply to all GPU nodes. In this configuration, there is no sharing of any kind. The configuration which defines an MPS strategy is called `test-mps` which I will activate on just a single node in a minute.

Deploy the GPU operator and see there are no MPS control daemons running because the default config is in effect.

```sh
$ k -n nvidia-gpu-operator get po
NAME                                                              READY   STATUS      RESTARTS   AGE
gpu-feature-discovery-cpp62                                       2/2     Running     0          105s
gpu-feature-discovery-kqrn4                                       2/2     Running     0          105s
gpu-operator-667764bfd6-6qqx4                                     1/1     Running     0          115s
nvidia-container-toolkit-daemonset-cmr2w                          1/1     Running     0          106s
nvidia-container-toolkit-daemonset-txfhc                          1/1     Running     0          106s
nvidia-cuda-validator-p8bh2                                       0/1     Completed   0          92s
nvidia-cuda-validator-q566j                                       0/1     Completed   0          75s
nvidia-dcgm-exporter-n4fv5                                        1/1     Running     0          105s
nvidia-dcgm-exporter-p8grw                                        1/1     Running     0          105s
nvidia-device-plugin-daemonset-2jc6f                              2/2     Running     0          106s
nvidia-device-plugin-daemonset-vnkkt                              2/2     Running     0          106s
nvidia-gpu-operator-node-feature-discovery-gc-7f54fcd4d-rdqlp     1/1     Running     0          115s
nvidia-gpu-operator-node-feature-discovery-master-bb9d8cd-zntfm   1/1     Running     0          115s
nvidia-gpu-operator-node-feature-discovery-worker-8ms87           1/1     Running     0          115s
nvidia-gpu-operator-node-feature-discovery-worker-qwcz4           1/1     Running     0          115s
nvidia-gpu-operator-node-feature-discovery-worker-sdxnf           1/1     Running     0          115s
nvidia-operator-validator-5sd9w                                   1/1     Running     0          106s
nvidia-operator-validator-zg882                                   1/1     Running     0          106s
```

Check the NVIDIA-related labels for one of the nodes. You will see the label `nvidia.com/device-plugin.config` will NOT be found on any of them because it isn't written by default. This is normal.

Now, assign that label with its value being the named configuration for your MPS strategy to one and only one of the nodes.

```sh
$ k label no ip-10-0-78-52.ec2.internal nvidia.com/device-plugin.config=test-mps
node/ip-10-0-78-52.ec2.internal labeled
```

Wait for 60 seconds and see how many and where the MPS control daemons were launched. This should only be on a single node.

```sh
$ k -n nvidia-gpu-operator get po -o wide | egrep mps
nvidia-device-plugin-mps-control-daemon-d489t                     2/2     Running     0          101s    10.0.81.130    ip-10-0-78-52.ec2.internal     <none>           <none>
```

The control daemon runs only on node `ip-10-0-78-52.ec2.internal` as expected, not the other node with a GPU.

Get back NVIDIA labels for that node to see the new values.

```sh
$ k get no ip-10-0-78-52.ec2.internal -o yaml | yq .metadata.labels | egrep ^nvidia.com/
nvidia.com/cuda.driver-version.full: 550.144.03
nvidia.com/cuda.driver-version.major: "550"
nvidia.com/cuda.driver-version.minor: "144"
nvidia.com/cuda.driver-version.revision: "03"
nvidia.com/cuda.driver.major: "550"
nvidia.com/cuda.driver.minor: "144"
nvidia.com/cuda.driver.rev: "03"
nvidia.com/cuda.runtime-version.full: "12.4"
nvidia.com/cuda.runtime-version.major: "12"
nvidia.com/cuda.runtime-version.minor: "4"
nvidia.com/cuda.runtime.major: "12"
nvidia.com/cuda.runtime.minor: "4"
nvidia.com/device-plugin.config: test-mps
nvidia.com/gfd.timestamp: "1740594709"
nvidia.com/gpu.compute.major: "7"
nvidia.com/gpu.compute.minor: "5"
nvidia.com/gpu.count: "1"
nvidia.com/gpu.deploy.container-toolkit: "true"
nvidia.com/gpu.deploy.dcgm: "true"
nvidia.com/gpu.deploy.dcgm-exporter: "true"
nvidia.com/gpu.deploy.device-plugin: "true"
nvidia.com/gpu.deploy.driver: "true"
nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
nvidia.com/gpu.deploy.node-status-exporter: "true"
nvidia.com/gpu.deploy.operator-validator: "true"
nvidia.com/gpu.family: turing
nvidia.com/gpu.machine: g4dn.xlarge
nvidia.com/gpu.memory: "15360"
nvidia.com/gpu.mode: compute
nvidia.com/gpu.present: "true"
nvidia.com/gpu.product: Tesla-T4
nvidia.com/gpu.replicas: "2"
nvidia.com/gpu.sharing-strategy: mps
nvidia.com/mig.capable: "false"
nvidia.com/mig.strategy: single
nvidia.com/mps.capable: "true"
nvidia.com/vgpu.present: "false"
```

You will see that labels `nvidia.com/gpu.replicas`, `nvidia.com/gpu.sharing-strategy`, and `nvidia.com/mps.capable` have been updated according to the configuration defined in `test-mps` having taken effect.

You now have a cluster with one node offering an exclusive GPU and another offering two replicas of a single GPU using MPS.

I hope this makes it clear now.

**Comment by santurini** [comment]
@chipzoller It worked! Thank you very much for the patience and the tutorial ❤️
Now if I want to use a shared gpu I just have to specify in the requests `nvidia.com/gpu.shared=1`, while if I want an entire gpu i just use `nvidia.com/gpu=1`, is it correct?

**Comment by chipzoller** [comment]
Yes

**Comment by santurini** [comment]
@chipzoller I was trying a simple test to see the gpu allocation but it is not able to find the devices:
```
apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  name: mps-env-test
spec:
  runtimeClassName: nvidia
  restartPolicy: OnFailure
  containers:
  - name: mps-env-test
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    command: ["sleep", "9999"]
    resources:
      limits:
        nvidia.com/gpu.shared: 1
```

With error:
```
0/2 nodes are available: 2 Insufficient nvidia.com/gpu.shared. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod.
```

If a try to use a node selector instead of `nvidia.com/gpu.shared: 1`:
```
apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  name: mps-env-test
spec:
  nodeSelector:
    nvidia.com/mps.capable: "true"
  runtimeClassName: nvidia
  restartPolicy: OnFailure
  containers:
  - name: mps-env-test
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    command: ["sleep", "9999"]
    resources:
      limits:
        nvidia.com/gpu: 1
```

I have a different error:
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: could not apply required modification to OCI specification: error modifying OCI spec: failed to inject CDI devices: unresolvable CDI devices management.nvidia.com/gpu=GPU-8a3eb582-5afc-e92d-bc66-41a3e9b835ec
```
