### ISSUE TITLE
Different PCI label from node feature discovery

### ISSUE THREAD

**Issue by Clockwork-Muse** [NVIDIA/k8s-device-plugin#1213]
I've installed Node Feature Discovery via:
```
helm install node-feature-discovery nfd/node-feature-discovery \
  --version=v0.17.2 \
  --namespace node-feature-discovery \
  --create-namespace
kubectl label --overwrite ns node-feature-discovery pod-security.kubernetes.io/enforce=privileged
```
... and then added this plugin via:
```
helm install nvidia-device-plugin nvdp/nvidia-device-plugin \
      --version=0.17.1 \
      --namespace nvidia-device-plugin \
      --create-namespace \
      --set gfd.enabled=true \
      --set nfd.enabled=false
```

... unfortunately the daemonset never spins up.  This seems to be because Node Feature Discovery is prepending the PCI device class to the label.  That is, my list of labels has this:
```
feature.node.kubernetes.io/pci-0300_10de.present=true
feature.node.kubernetes.io/pci-0380_8086.present=true
feature.node.kubernetes.io/system-os_release.ID=talos
feature.node.kubernetes.io/system-os_release.VERSION_ID=v1.9.4
kubernetes.io/arch=amd64
kubernetes.io/os=linux
```
.... whereas the [expected label in the helm chart is](https://github.com/NVIDIA/k8s-device-plugin/blob/adc69dce1839b831dfffc6337dd174833f0c743e/deployments/helm/nvidia-device-plugin/values.yaml#L69):
```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        # On discrete-GPU based systems NFD adds the following label where 10de is the NVIDIA PCI vendor ID
        - key: feature.node.kubernetes.io/pci-10de.present
```

... I'm not quite sure what the best option overall here is.
Note that [there's a way to configure the formatting of PCI device labels](https://github.com/kubernetes-sigs/node-feature-discovery/pull/550), although this doesn't seem to have happened at all in the chart.  So updating the chart to a current version is likely to break things. 

<hr />

Note that I can't use the GPU Operator because it's not (quite yet) supported on Talos, although I'm not sure that would "solve" the issue.
