### ISSUE TITLE
Multiple GPUs are visible in a container despite setting limits in Kubernetes manifest

### ISSUE THREAD

**Issue by tintin-newb** [NVIDIA/k8s-device-plugin#1294]
# Setup
I am using microk8s 1.32.3. I have 2 nodes in my cluster. The first is my local system which is the master node and the other is a server with 2 GPUs (NVIDIA RTX 3080) that is a worker. I am deploying DeepStream instances in a Pod using the manifest shown below. For multiple deployments I am changing the names and necessary labels as `app-deepstream-1`, `app-deepstream-2` and so on.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: app-deepstream-1                                # modify
  labels:
    name: app-deepstream-1                              # modify
    family: app-deepstream
spec:
  restartPolicy: Always
  runtimeClassName: nvidia
  nodeSelector:
    nvidia.com/gpu.present: "true"
  containers:
    - name: app-ai
      image: 192.168.65.106:32000/nvcr.io/nvidia/deepstream
      securityContext:
        privileged: true
      imagePullPolicy: IfNotPresent
      tty: true
      resources:
        limits:
          nvidia.com/gpu: 1
      workingDir: /opt/app/ai-app-prod/
      command: ["bash", "run.sh"]
      volumeMounts:
        - name: app-volume
          mountPath: /opt/app/
  volumes:
    - name: app-volume
      persistentVolumeClaim:
        claimName: app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-deepstream-svc-1                           # modify
  labels:
    name: app-deepstream-svc-1                         # modify
    family: app-deepstream
spec:
  type: NodePort
  selector:
    name: app-deepstream-1                             # modify
  ports:
    - port: 9000           # ClusterIP port
      targetPort: 9000     # Container port
      protocol: TCP
```
I have enabled gpu and registry add-ons in microk8s. The node with GPU is correctly labelled and I have checked that mig capability is marked as false (this will become important later).

I needed a custom auto-scaler that scales the number of Pods up or down based on the number of streams running in an instance. I have used `Python 3.10` with the `kubernetes` package for this. The upscale script and the downscale script just modify the manifest template and deploy the Pod and the service in the cluster. I face no issues when I run these scripts at all. This is just a wrapper of the `v1.create_namespaced_pod()` and `v1.delete_namespaced_pod()` provided by the Kubernetes library in a try-except block.

**Note**: The DeepStream app config (present in the mount) specifies the GPU index which is set to 0 with the expectation that a single GPU will be assigned and hence visible to the container.

# Problem
The Pods and respective services are deployed without any problems even when I deploy multiple Pods. Once multiple pods are deployed and in the `Running` phase I checked `nvidia-smi` in my GPU node. **I found out that both DeepStream apps in the 2 pods that are deployed are running on the same GPU (0).**

The interesting thing is when I check `microk8s kubectl describe <node>` I can see that 2 GPUs have been allocated as shown below.
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                365m (2%)   0 (0%)
  memory             320Mi (0%)  5632Mi (4%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
  nvidia.com/gpu     2           2
```

Now when I go inside a container and check with `nvidia-smi` I see that 2 GPUs are visible as shown below.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.230.02             Driver Version: 535.230.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   34C    P8              16W / 340W |    564MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3080        Off | 00000000:03:00.0 Off |                  N/A |
|  0%   30C    P8              18W / 340W |     12MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

If nvidia-device-plugin is supposed to set CUDA_VISIBLE_DEVICES environment variable that does not seem to be working correctly. 

# Expectation
Each GPU should be exclusively allocated to each container that requests a GPU and it should run on that GPU only. I thought GPUs are not shared by default unless we enable MIGs or time-slicing explicitly.

 1. What is the possible reason for this behaviour?
 2. If there are debugging steps you want me to perform for a better understanding please let me know.
 3. If someone can provide a solution to get the expected outcome I will be grateful.

This is the first time I am using Kubernetes and microk8s so I am unsure what the root problem might be.

**Comment by MikeSpreitzer** [comment]
I also have this problem, in an even simpler setup. I am not relying on the Kubernetes Pod scheduler, I am directly setting the decisions in the PodSpec. When creating the Pod, I supply `spec.nodeName` and an entry in `spec.containers[0].env` that says "NVIDIA_VISIBLE_DEVICES=1" (that value is a list of GPU _indices_). Even so, `nvidia-smi` inside the running container reports two GPUs. In my case, it is an nvidia L40S.

```console
mspreitz@mjs13 vcp-cache-manager % kubectl get pod it-jm3bbhbhe9-granite-3-3-2b-instruct-deployment-vllm-5fb46sldc -o yaml
apiVersion: v1
kind: Pod
metadata:
...
spec:
...
  containers:
  - command:
    - vllm
    - serve
    - ibm-granite/granite-3.3-2b-instruct
    - --host
    - 0.0.0.0
    - --port
    - "8000"
    - --enable-sleep-mode
    env:
    - name: HF_HOME
      value: /tmp
    - name: LMCACHE_LOG_LEVEL
      value: DEBUG
    - name: NVIDIA_VISIBLE_DEVICES
      value: "1"
    - name: VLLM_SERVER_DEV_MODE
      value: "1"
    - name: VLLM_USE_V1
      value: "1"
...
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        cpu: "6"
        memory: 16Gi
        nvidia.com/gpu: "1"
...
  nodeName: fmaas-platform-eval-2rrkv-worker-l40-2-bqqbj
...
  schedulerName: default-scheduler
```

```console
mspreitz@mjs13 vcp-cache-manager % kubectl exec it-jm3bbhbhe9-granite-3-3-2b-instruct-deployment-vllm-5fb46sldc -- nvidia-smi    
Tue Jun 24 11:45:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.144.03             Driver Version: 550.144.03     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    On  |   00000000:04:01.0 Off |                    0 |
| N/A   51C    P0            114W /  350W |   42091MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA L40S                    On  |   00000000:04:02.0 Off |                    0 |
| N/A   37C    P8             37W /  350W |       4MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       119      C   /usr/bin/python3                                0MiB |
+-----------------------------------------------------------------------------------------+
```

The Prometheus metric DCGM_FI_DEV_GPU_UTIL shows GPU index 0 in use by my Pod, index 1 not used by any Pod.

This is an OpenShift 4.16.36 (Kubernetes 1.29.11) cluster.

nvidia GPU operator 24.9.2.
RedHat OpenShift AI (operator) 2.16.0

**Comment by MikeSpreitzer** [comment]
```console
mspreitz@mjs13 ~ % kubectl exec it-jm3bbhbhe9-granite-3-3-2b-instruct-deployment-vllm-5fb46sldc -- printenv | grep VISIBLE         
NVIDIA_VISIBLE_DEVICES=1
```

**Comment by tintin-newb** [comment]
I have investigated further after I published this post. 
1. I checked whether nvidia-device-plugin was working correctly or not. To do this I checked the value of the environment variable `NVIDIA_VISIBLE_DEVICES` inside each container. **The values are unique in each container as it should be**.  
```
nvidia-smi -L          # executed in GPU host
GPU 0: NVIDIA GeForce RTX 3080 (UUID: GPU-e2a7d5f1-f4e4-9585-61ee-b64cce744228)
GPU 1: NVIDIA GeForce RTX 3080 (UUID: GPU-95f9f092-00da-bbb0-7d4e-180cd0f6d7ff)

# NVIDIA_VISIBLE_DEVICES in each container
app-deepstream-1: GPU-e2a7d5f1-f4e4-9585-61ee-b64cce744228
app-deepstream-2: GPU-95f9f092-00da-bbb0-7d4e-180cd0f6d7ff
```
Despite this, when I do `nvidia-smi` I can see both the GPUs in both containers which I don't believe should be happening.

2. I was using the nvidia-runtime-container set up by the add-on. Since, I have nvidia-container-runtime in my host I thought maybe there is some interference. Hence, I switched to the host runtime using the steps mentioned [here](https://microk8s.io/docs/addon-gpu#p-20002-use-host-nvidia-container-runtime). This did not solve the issue. I have attached the `containerd.toml` and `containerd-template.toml` for reference (using .txt extension as .toml extension is not allowed)

[containerd.txt](https://github.com/user-attachments/files/20896484/containerd.txt)
[containerd-template.txt](https://github.com/user-attachments/files/20896483/containerd-template.txt)

3. Finally, I came across [these settings](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#microk8s) recommended by the official NVIDIA documentation of the gpu operator. I injected the options during install. The validator got stuck in init:3/4 state and hence, I could not verify whether this solved the issue.

4. I also added a RuntimeClass to the manifest to select the nvidia runtime. This too did not resolve the issue.
``` yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia  # <-- This name MUST match what you put in runtimeClassName
handler: nvidia  # <-- This name MUST match a runtime defined in your containerd-template.toml
---
apiVersion: v1
kind: Pod
metadata:
  name: app-deepstream-1                                # modify
  labels:
    name: app-deepstream-1                              # modify
    family: app-deepstream
spec:
  restartPolicy: Always
  runtimeClassName: nvidia
  nodeSelector:
    nvidia.com/gpu.present: "true"
  containers:
    - name: app-ai
      image: 192.168.65.106:32000/nvcr.io/nvidia/deepstream
      securityContext:
        privileged: true
      imagePullPolicy: IfNotPresent
      tty: true
      resources:
        limits:
          nvidia.com/gpu: 1
      workingDir: /opt/app/ai-app-prod/
      command: ["bash", "run.sh"]
      volumeMounts:
        - name: app-volume
          mountPath: /opt/app/
  volumes:
    - name: app-volume
      persistentVolumeClaim:
        claimName: app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-deepstream-svc-1                           # modify
  labels:
    name: app-deepstream-svc-1                         # modify
    family: app-deepstream
spec:
  type: NodePort
  selector:
    name: app-deepstream-1                             # modify
  ports:
    - port: 9000           # ClusterIP port
      targetPort: 9000     # Container port
      protocol: TCP
```

## Inspect tarball (post deployment of 2 Pods): 

[inspection-report-20250625_105200.tar.gz](https://github.com/user-attachments/files/20896841/inspection-report-20250625_105200.tar.gz)
