### ISSUE TITLE
How two containers could share 1 GPU?

### ISSUE THREAD

**Issue by Birch-san** [NVIDIA/k8s-device-plugin#1301]
Is there a way to deploy multiple containers sharing the same GPUs?

For example, 2 containers using 1 GPU.  
So that we can run a container for our primary service, but also another contaier for a secondary service that it small enough to fit comfortably within the same resources.

It looks like GPU limits are specified at the container level:

```yml
containers:
  - image: my-cool-service
    resources:
      limits:
        nvidia.com/gpu: "1"
  - image: another-cool-service-really-small-lemme-share-that-gpu
```

is there any way for a container to express "I want 1 GPU too, put me on the same GPU the other container got" or something like that?
