### ISSUE TITLE
Multiple pods share one GPU

### ISSUE THREAD

**Issue by yechnlin** [NVIDIA/k8s-device-plugin#134]
### Issue or feature description
***Nvidia GeForce GTX 1050 Ti** is ready on my host, also nvidia k8s-device-plugin is running well, i can see that `nvidia.com/gpu` is ready,
```
# kubectl describe node k8s
...
Capacity:
 cpu:                 8
 ephemeral-storage:   75881276Ki
 hugepages-1Gi:       0
 hugepages-2Mi:       0
 memory:              16362632Ki
 nvidia.com/gpu:      1
Allocatable:
 cpu:                 8
 ephemeral-storage:   69932183846
 hugepages-1Gi:       0
 hugepages-2Mi:       0
 memory:              16260232Ki
 nvidia.com/gpu:      1
```
However, `nvidia.com/gpu` resource value is only `1`, so  `pod-1` hold all `Nvidia GeForce GTX 1050 Ti` GPU resource, that `pod-2` can not be deployed because there is no free `nvidia.com/gpu` resource.

So, can GPU resource be shared with multiple pods?

Thanks

**Comment by yechnlin** [comment]
@klueska

**Comment by klueska** [comment]
Do you only have 1 GPU on the machine, but are expecting to be able to share that GPU with multiple containers/pods? While technically possible (because of a weirdness in the design of the Nvidia GPU container stack), it actually goes against the device / resource allocation model of Kubernetes.

Can you be a bit more precise in what you are asking for here?

**Comment by estherxyz** [comment]
> Do you only have 1 GPU on the machine, but are expecting to be able to share that GPU with multiple containers/pods? While technically possible (because of a weirdness in the design of the Nvidia GPU container stack), it actually goes against the device / resource allocation model of Kubernetes.
> 
> Can you be a bit more precise in what you are asking for here?

Hi, klueska,

I am also interesting about this topic.
As your response, I have other question about gpu management on k8s.
I do not understand why design of the NVIDIA GPU against the gpu resource allocation on k8s?
Is because of now nvidia gpu plugin allocate gpu use integer? Or is because of other reason?

Thanks.

**Comment by yechnlin** [comment]
Hi Klueska,

> Do you only have 1 GPU on the machine, but are expecting to be able to share that GPU with multiple containers/pods? While technically possible (because of a weirdness in the design of the Nvidia GPU container stack), it actually goes against the device / resource allocation model of Kubernetes.

> Can you be a bit more precise in what you are asking for here?

 i only have 1 GPU on my machine, and i want to share that GPU with multiple containers/pods.

from https://github.com/NVIDIA/nvidia-docker/wiki#can-i-share-a-gpu-between-multiple-containers , i can see that 1 GPU can be shared between multiple containers, so i guess that it also can be applied to k8s containers/pods, unfortunately, it can not.

Thanks.

**Comment by klueska** [comment]
There is currently no supported way to share GPUs in Kubernetes. I've heard of a number of different workarounds,but there is no official support for this upstream.

**Comment by achernev** [comment]
Can this limitation be circumvented by having all GPU tenants as containers in the same pod?

**Comment by yzs981130** [comment]
A dirty hack of it: https://github.com/yzs981130/k8s-device-plugin/commit/760d0f2569c22ba79dd8a4b896a059d8e4fa80d8

**Comment by yechnlin** [comment]
@yzs981130 你好, same thought with you, i also use virtual devices id for sharing one GPU, but it just a workaround.

**Comment by ra1ski** [comment]
> @yzs981130 你好, same thought with you, i also use virtual devices id for sharing one GPU, but it just a workaround.

can you share the way you handle sharing one GPU ?

**Comment by achernev** [comment]
@ra1ski Probably not the answer you are looking for but here's my workaround running all GPU-utilising containers in the same pod, alongside one which gets the GPU, then sets a ConfigMap item with the GPU ID that the others then read and set as their `NVIDIA_VISIBLE_DEVICES` accordingly.

The GPU "hog" (the container which gets the GPU) executable:

```python
#!/usr/bin/env python3

from kubernetes import client, config
from kubernetes.client.rest import ApiException
from pprint import pprint
import os
import time

config.load_incluster_config()

api_instance = client.CoreV1Api()
name = 'gpu-config'
namespace = open('/var/run/secrets/kubernetes.io/serviceaccount/namespace').read()
body = client.V1ConfigMap(
    api_version='v1',
    kind='ConfigMap',
    data=dict(NVIDIA_VISIBLE_DEVICES=os.environ['NVIDIA_VISIBLE_DEVICES']),
    metadata=dict(name=name),
)

try:
    api_response = api_instance.replace_namespaced_config_map(name, namespace, body, pretty='true')
    pprint(api_response)
except ApiException as e:
    print('Exception when calling CoreV1Api->replace_namespaced_config_map: %s\n' % e)

print('Sleeping forever')

while True:
    time.sleep(1)
```

Dockerfile for that:

```docker
FROM debian:stretch-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-setuptools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 --no-cache-dir install kubernetes

WORKDIR /usr/src/app
COPY set-configmap.py .

CMD ["python3", "set-configmap.py"]
```

Kubernetes YAMLs:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-sharers
spec:
  template:
    spec:
      containers:
        # This container is the one to which the GPU will be assigned.
        # It then takes the NVIDIA_VISIBLE_DEVICES env var and pushes it onto a ConfigMap.
        # The other two containers then load that environment variable from the ConfigMap.
        - name: gpuhog
          resources:
            limits:
              nvidia.com/gpu: 1

        - name: gpu-container-1
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              valueFrom:
                configMapKeyRef:
                  name: gpu-config
                  key: NVIDIA_VISIBLE_DEVICES

        - name: gpu-container-2
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              valueFrom:
                configMapKeyRef:
                  name: gpu-config
                  key: NVIDIA_VISIBLE_DEVICES
```
