### ISSUE TITLE
0/2 nodes are available: 2 Insufficient nvidia.com/gpu

### ISSUE THREAD

**Issue by nikosep** [NVIDIA/k8s-device-plugin#159]
Facing this old issue. 
I have gone through all the relevant workarounds, although still the issue persists.

Kubernetes version: 1.14
Docker version on GPU node: 19.03.6
GPU node: 4 x GTX1080Ti

I am trying to deploy this example:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow-gpu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tensorflow-gpu
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-418/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-418
        name: lib
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        name: libcuda-so-1
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so
        name: libcuda-so
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest-gpu
        ports:
        - containerPort: 8888
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          name: libcuda-so-1
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
          name: libcuda-so
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-gpu-service
  labels:
    app: tensorflow-gpu
spec:
  selector:
    app: tensorflow-gpu
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
---
```
And I am getting the following error:
**0/2 nodes are available: 2 Insufficient nvidia.com/gpu**

Specifying the GPU node explicitly on the deployment yaml I am getting the following error:
**Update plugin resources failed due to requested number of devices unavailable for nvidia.com/gpu. Requested: 1, Available: 0, which is unexpected.**  

/etc/docker/daemon.json on GPU node:
```
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```
I have restarted docker and kubelet.

I am using this nvidia daemon:
https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta4/nvidia-device-plugin.yml

Should I 
-label somehow the GPU node that has nvidia gpu?
-restart master node?

Any help here is more than welcome !
