### ISSUE TITLE
Can't deploy NVIDIA device plugin on k8s 1.8.6 because could not load NVML library

### ISSUE THREAD

**Issue by wydwww** [NVIDIA/k8s-device-plugin#19]
# version
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubelet --version
Kubernetes v1.8.6

NVIDIA-SMI 375.26

$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
OS system is Debian 9.
GPU: Tesla K40m.
CUDA: Cuda compilation tools, release 8.0, V8.0.61
# error
I installed Nvidia-docker according to the [Debian instrunctions](https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)) and https://github.com/NVIDIA/nvidia-docker/issues/516 and can run `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi` successfully. I set Nvidia as default-runtime and enabled the DevicePlugins feature gate on my 2-node k8s cluster equipped with Tesla K40m.

But when I run 
```
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.8/nvidia-device-plugin.yml
``` 
or
```
docker run --security-opt=no-new-privileges --cap-drop=ALL --network=none -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.8
```
they gave error:
```
2018/01/05 12:25:01 Loading NVML
2018/01/05 12:25:01 Failed to start nvml with error: could not load NVML library.
```
The output of ldconfig is
```
$ ldconfig -p | grep nvidia-ml
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so.1 (libc6) => /usr/lib32/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
	libnvidia-ml.so (libc6) => /usr/lib32/libnvidia-ml.so
```

I checked other issues like https://github.com/NVIDIA/nvidia-docker/issues/74 and https://github.com/NVIDIA/nvidia-docker/issues/470, they failed to run nvidia-docker but I can.

Another strange thing is that there is no `nvidia-device-plugin` in my path and the output of `locate nvidia-device-plugin` is blank.

Could please me check what went wrong?
Thanks!

**Comment by wydwww** [comment]
I did all these GPU Nvidia-docker stuff after I already setup a k8s cluster with kubeadm.

**Comment by wydwww** [comment]
Just found it is same with #11 
Closed

**Comment by wydwww** [comment]
Try `docker run --runtime=nvidia -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.8` command and output is:
```
2018/01/06 05:06:23 Loading NVML
2018/01/06 05:06:32 Fetching devices.
nvidia-device-plugin: symbol lookup error: nvidia-device-plugin: undefined symbol: nvmlDeviceGetPciInfo_v3
```

I searched but didn't get any information.

**Comment by RenaudWasTaken** [comment]
From past issues related to NVML my first guess would be to say that your GPU might be too old.
Though @flx42 knows more about such nvml errors and should be able to confirm / infirm this.

**Comment by wydwww** [comment]
And I can run TensorFlow GPU through docker:
```
nvidia-docker run -it gcr.io/tensorflow/tensorflow:latest-gpu bash
```

@RenaudWasTaken thanks for your help, this GPU usually works fine when I do some TF training and nv-docker ops.

**Comment by wydwww** [comment]
I tried to build k8s-device-plugin without docker, and the error info was:
```
$ ./k8s-device-plugin
2018/01/08 14:10:40 Loading NVML
2018/01/08 14:10:49 Fetching devices.
2018/01/08 14:10:49 Starting FS watcher.
2018/01/08 14:10:49 Failed to created FS watcher.
```

**Comment by flx42** [comment]
> If executed with sudo, it will stuck here forever: [...]

This is actually the normal output, everything should be working at this point.

**Comment by wydwww** [comment]
@flx42 Thanks!

But here comes another problem. I deployed this yaml file according to k8s doc (added volume because some error message):
```
apiVersion: v1
kind: Pod
metadata:
  name: tf-gpu
spec:
  restartPolicy: OnFailure
  containers:
    - name: tf-gpu
      image: "gcr.io/tensorflow/tensorflow:latest-gpu"
      command: ["python"]
      args: ["-u", "-c", "import tensorflow"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
      volumeMounts:
      - name: libcuda-so-1
        mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
      - name: libcuda-so
        mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
      - name: libnvidia-fatbinaryloader
        mountPath: /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.26
  restartPolicy: Never
  volumes:
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so
```
Then I can exec into bash through `kubectl exec -it tf-gpu bash`
and jupyter can't find the GPU:
```
root@tf-gpu:/notebooks# jupyter nbconvert --execute 1_hello_tensorflow.ipynb

[NbConvertApp] Converting notebook 1_hello_tensorflow.ipynb to html
[NbConvertApp] Executing notebook with kernel: python
2018-01-08 19:55:26.294390: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-08 19:55:26.296075: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-01-08 19:55:26.296137: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:152] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
[NbConvertApp] Writing 283296 bytes to 1_hello_tensorflow.html
```
I'm confused what went wrong.
