### ISSUE TITLE
Pod can access Node GPU resource even though no GPU request/limit parameter was specified in the Kubernetes POD Spec.

### ISSUE THREAD

**Issue by khatrig** [NVIDIA/k8s-device-plugin#195]
### 1. Issue description
**Pod can access GPU resource even though no GPU request/limit parameter was specified in the POD Spec.**

### 2. Steps to reproduce the issue

kubectl apply -f gpu.yaml

**gpu.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-resource-test
spec:
  containers:
  - name: "cuda"
    image: "nvidia/cuda"
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: "linux"
    nvidia.com/node_type: "gpu_tester"
```

**k exec -it gpu-resource-test -- nvidia-smi**                                                             
```
Tue Sep 15 10:45:44 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.37       Driver Version: 450.37       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K2200        Off  | 00000000:65:00.0 Off |                  N/A |
| 42%   33C    P8     1W /  39W |      0MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

### 3. Additional Information 
```
K8S version - 1.16.3
Docker version - 19.03
Device Plugin Version: nvidia/k8s-device-plugin:1.0.0-beta4
OS DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
Kernel Version - 4.15.0-72-generic
```
