### ISSUE TITLE
The device plugin's DaemonSet stucks in "ContainerCreating" state 

### ISSUE THREAD

**Issue by highreso** [NVIDIA/k8s-device-plugin#220]
### Issue or feature description
I now engaging in constructing mini HPC system with Nvidia k8s device plugin.
The system is composed of a Master machine(Ubuntu18.04, GTX 1080 * 1) and a Worker machine(Ubuntu18.04, GTX 1060 * 2).
 
When the Worker machine with GTX 1060 * 1, the device plugin worked successfully.
But after I added another GTX1060 on the Worker machine(meaning, the slave machine composed of 2 GTX1060 GPUs), it doesn't.
The status of the daemon set pod keeps `ContainerCreating`  more than 20 minutes.

### Detail of the issue
1. I created daemon set pod with:
` kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.7.3/nvidia-device-plugin.yml`

2. I confirmed the daemon set pod create successfully, because the log said:
```bash
daemonset.apps/nvidia-device-plugin-daemonset created.
```

3. I checked whether the pod created or not with:
`kubectl get pods --all-namespaces -o wide | grep nvidia`

```bash
kube-system   nvidia-device-plugin-daemonset-g2h7g               0/1     ContainerCreating   0          20m   <none>           xxx     <none>           <none>
```

The status "ContainerCreating" remains more than 20 minites. 

I would be happy if you tell me how to solve it.
Thank you in advance.

**Comment by klueska** [comment]
What is it stuck on? i.e. what is the output of:
```
kubectl describe pod -n kube-system nvidia-device-plugin-daemonset-g2h7g 
```

**Comment by highreso** [comment]
Thank you for kindly reply, but since I tried creating the daemon set time and time again and I did it with lack of my knowledge, even getting `coredns` to work failed.

I mean, after `kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.7.3/nvidia-device-plugin.yml`, it outputs:

```
    IP               NODE                       NOMINATED NODE   READINESS GATES
kube-system   coredns-74ff55c5b-hgx4c                            0/1     ContainerCreating   0          4m19s   <none>           xmaster-tb350-btc   <none>           <none>
kube-system   coredns-74ff55c5b-zwjdc                            0/1     ContainerCreating   0          4m19s   <none>           xmaster-tb350-btc   <none>           <none>
kube-system   etcd-xmaster-tb350-btc                      1/1     Running             0          4m26s   192.168.11.125   xmaster-tb350-btc   <none>           <none>
kube-system   kube-apiserver-xmaster-tb350-btc            1/1     Running             0          4m26s   192.168.11.125   xmaster-tb350-btc   <none>           <none>
kube-system   kube-controller-manager-xmaster-tb350-btc   1/1     Running             0          4m26s   192.168.11.125   xmaster-tb350-btc   <none>           <none>
kube-system   kube-proxy-8dp2s                                   1/1     Running             0          4m19s   192.168.11.125   xmaster-tb350-btc   <none>           <none>
kube-system   kube-proxy-m9ztn                                   1/1     Running             0          3m42s   192.168.11.5     xslave-tb350-btc    <none>           <none>
kube-system   kube-scheduler-xmaster-tb350-btc            1/1     Running             0          4m26s   192.168.11.125   xmaster-tb350-btc   <none>           <none>
```

meaning, `coredns` between the master machine and the worker(slave) doesn't work.

I don't the reason. But it must be my fault, during setting network between the master and slave.

thank you.

**Comment by highreso** [comment]
Sorry for confusing, but I made a small step.
After I created `CALICO` pod, all these problem above solved.

The out put of `kubectl get pods --all-namespaces -o wide | grep nvidia`:
```
kube-system   nvidia-device-plugin-daemonset-bnjmv               1/1     Running   0          3m53s   192.168.214.129   xslave-tb350-btc    <none>           <none>
```

and here is the configuration yaml file for CALICO:
```yaml
--------
  # Set MTU for the Wireguard tunnel device.
  - name: FELIX_WIREGUARDMTU
    valueFrom:
      configMapKeyRef:
        name: calico-config
        key: veth_mtu
  # The default IPv4 pool to create on startup if none exists. Pod IPs will be
  # chosen from this range. Changing this value after installation will have
  # no effect. This should fall within `--cluster-cidr`.
  - name: CALICO_IPV4POOL_CIDR
    value: "192.168.0.0/16"  # kubeadm init時の--pod-network-cidrの引数と同じ
  # Disable file logging so `kubectl logs` works.
  - name: CALICO_DISABLE_FILE_LOGGING
    value: "true"
  # Set Felix endpoint to host default action to ACCEPT.
  - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
  - -------
```

I think the issue was caused by I didn't create the CALICO pod appropriately.
But to be honest, I don't know the reason why the issue were solved exactly.

Thank for your time.
And sorry for getting you confused.
