### ISSUE TITLE
Use containerd instead of docker for GPU support on kubernetes

### ISSUE THREAD

**Issue by DrissiReda** [NVIDIA/k8s-device-plugin#275]
Is it possible to use containerd instead of docker for gpu support? Since kubernetes has moved away from Docker. I think it might be benefitial to drop it even while using GPUs. Or is there some problem with containerd and nvidia container runtime? Because I can run containers with `ctr` command directly and gpu support without a hitch.

**Comment by elezar** [comment]
Hi @DrissiReda, yes, one can use `containerd` to run GPU-enabled containers. In order to do so one needs to add a new "runtime" to the config file that points to the `nvidia-container-runtime` (mirroring what is done for `docker`). 

You could check the documentation here: https://docs.nvidia.com/datacenter/cloud-native/kubernetes/install-k8s.html#install-nvidia-container-toolkit-nvidia-docker2 for further instructions.

**Comment by DrissiReda** [comment]
Thanks for your quick reply, I have done so:

I'm running CentOS 8.4, with a Tesla K80. I installed cuda from official nvidia site.
I added this conf to my containerd conf:

<details>

<summary> <code> config.toml </code> </summary>

```toml
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          runtime_engine = ""
          runtime_root = ""
          privileged_without_host_devices = false
          base_runtime_spec = ""
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
       	  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
            privileged_without_host_devices = false
            runtime_engine = ""
            runtime_root = ""
            runtime_type = "io.containerd.runc.v1"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
              BinaryName = "/usr/bin/nvidia-container-runtime-hook"
              SystemdCgroup = true

```

</details>

I had to switch `/usr/bin/nvidia-container-runtime` to `/usr/bin/nvidia-container-runtime-hook` because the original isn't available in my system.

I know it works, because using this command gives me the `nvidia-smi` expected output.

```bash
ctr run --rm --gpus 0 -t docker.io/nvidia/cuda:11.0-base cuda-11.0-base nvidia-smi
```

But when I install the device plugin I get this output of the daemonSet:

```bash
2021/11/10 14:12:26 Loading NVML
2021/11/10 14:12:26 Failed to initialize NVML: could not load NVML library.
2021/11/10 14:12:26 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2021/11/10 14:12:26 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2021/11/10 14:12:26 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
```

**Comment by elezar** [comment]
Hi @DrissiReda  you may need to install the `nvidia-container-runtime` package for your distribution. The `nvidia-container-runtime` executable and the `nvidia-container-runtime-hook` executable are **NOT** equivalent.

The `nvidia-container-runtime` is a lightweight shim around `runc` which injects the `nvidia-container-runtime-hook` as a prestart hook. This then invokes the `nvidia-container-cli` to ensure that the required modifications are made to the container. See for example: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html#architecture

**Comment by DrissiReda** [comment]
Thanks @elezar  but I already installed it on my centOS, I also have the files:

```bash
/usr/bin/nvidia-container-cli 
/usr/bin/nvidia-container-runtime-hook 
/usr/bin/nvidia-container-toolkit
```

When I try: `dnf -y install nvidia-container-runtime` I get:

```bash
Last metadata expiration check: 0:03:17 ago on mer. 10 nov. 2021 15:33:49 UTC.
Package nvidia-container-toolkit-1.5.1-2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

```

Is this normal?

**Comment by elezar** [comment]
This is not normal. Which NVIDIA repos are configured on your system? You should be able to add the [`nvidia-container-runtime.repo`](https://github.com/NVIDIA/nvidia-container-runtime/centos8/nvidia-container-runtime.repo) file or the `nvidia-docker2.repo` file as described [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-centos-7-8)

and then have the `nvidia-container-runtime` package available.

**Comment by DrissiReda** [comment]
that's what I'm using, and it says that the `nvidia-container-runtime` package is already installed.

Here are its contents:

<details> 

<summary> <code> nvidia-docker.repo </code> </summary>

```ini
[libnvidia-container]
name=libnvidia-container
baseurl=https://nvidia.github.io/libnvidia-container/stable/centos8/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[libnvidia-container-experimental]
name=libnvidia-container-experimental
baseurl=https://nvidia.github.io/libnvidia-container/experimental/centos8/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=0
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[nvidia-container-runtime]
name=nvidia-container-runtime
baseurl=https://nvidia.github.io/nvidia-container-runtime/stable/centos8/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/nvidia-container-runtime/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[nvidia-container-runtime-experimental]
name=nvidia-container-runtime-experimental
baseurl=https://nvidia.github.io/nvidia-container-runtime/experimental/centos8/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=0
gpgkey=https://nvidia.github.io/nvidia-container-runtime/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[nvidia-docker]
name=nvidia-docker
baseurl=https://nvidia.github.io/nvidia-docker/centos8/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/nvidia-docker/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

```

</details>

**Comment by elezar** [comment]
When specifying the `--gpus 0` flag to `ctr`, the `nvidia-container-runtime` is not used to modify the OCI spec (inserting the hook). Instead, `ctr` inserts the hook itself before invoking `runc`.

Could you download the `rpm` directly from https://github.com/NVIDIA/nvidia-container-runtime/blob/gh-pages/stable/centos8/x86_64/nvidia-container-runtime-3.5.0-1.x86_64.rpm and install it?

This should unblock you while I dig a bit further into what is causing this issue.

**Comment by DrissiReda** [comment]
Thanks @elezar  I have used your trick (specifying the version) to install the dependency, it installs correctly and I have the `nvidia-container-runtime` binary, but after changing my conf, nothing changes, I can still only use it with containerd with `--gpus 0`. And the daemonSet still has the same output, I rebooted the machine for extra good measure. For reference this is my containerd conf file:


<details>
<summary> <code> config.toml </code> </summary>

```toml
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
plugin_dir = ""
disabled_plugins = []
required_plugins = []
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  tcp_address = ""
  tcp_tls_cert = ""
  tcp_tls_key = ""
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[ttrpc]
  address = ""
  uid = 0
  gid = 0

[debug]
  address = ""
  uid = 0
  gid = 0
  level = ""

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[timeouts]
  "io.containerd.timeout.shim.cleanup" = "5s"
  "io.containerd.timeout.shim.load" = "5s"
  "io.containerd.timeout.shim.shutdown" = "3s"
  "io.containerd.timeout.task.state" = "2s"

[plugins]
  [plugins."io.containerd.gc.v1.scheduler"]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
  [plugins."io.containerd.grpc.v1.cri"]
    disable_tcp_service = true
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    stream_idle_timeout = "4h0m0s"
    enable_selinux = false
    selinux_category_range = 1024
    sandbox_image = "k8s.gcr.io/pause:3.2"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    disable_cgroup = false
    disable_apparmor = false
    restrict_oom_score_adj = false
    max_concurrent_downloads = 3
    disable_proc_mount = false
    unset_seccomp_profile = ""
    tolerate_missing_hugetlb_controller = true
    disable_hugetlb_controller = true
    ignore_image_defined_volumes = false
    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "overlayfs"
      default_runtime_name = "runc"
      no_pivot = false
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
        privileged_without_host_devices = false
        base_runtime_spec = ""
      [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
        privileged_without_host_devices = false
        base_runtime_spec = ""
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          runtime_engine = ""
          runtime_root = ""
          privileged_without_host_devices = false
          base_runtime_spec = ""
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
              privileged_without_host_devices = false
              runtime_engine = ""
              runtime_root = ""
              runtime_type = "io.containerd.runc.v1"
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
                BinaryName = "/usr/bin/nvidia-container-runtime"
                SystemdCgroup = true
    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
      max_conf_num = 1
      conf_template = ""
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
    [plugins."io.containerd.grpc.v1.cri".image_decryption]
      key_model = ""
    [plugins."io.containerd.grpc.v1.cri".x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""
  [plugins."io.containerd.internal.v1.opt"]
    path = "/opt/containerd"
  [plugins."io.containerd.internal.v1.restart"]
    interval = "10s"
  [plugins."io.containerd.metadata.v1.bolt"]
    content_sharing_policy = "shared"
  [plugins."io.containerd.monitor.v1.cgroups"]
    no_prometheus = false
  [plugins."io.containerd.runtime.v1.linux"]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = ""
    no_shim = false
    shim_debug = false
  [plugins."io.containerd.runtime.v2.task"]
    platforms = ["linux/amd64"]
  [plugins."io.containerd.service.v1.diff-service"]
    default = ["walking"]
  [plugins."io.containerd.snapshotter.v1.devmapper"]
    root_path = ""
    pool_name = ""
    base_image_size = ""
    async_remove = false

```
