### ISSUE TITLE
Pod unable to schedule to gpu nodes

### ISSUE THREAD

**Issue by HirazawaUi** [NVIDIA/k8s-device-plugin#283]
I created a GPU nodes in openshift3.11, I follow the https://github.com/zvonkok/origin-ci-gpu/blob/release-3.11/doc/How%20to%20use%20GPUs%20with%20DevicePlugin%20in%20OpenShift%203.11%20.pdf, initializes the GPU node and adds it to the OCP cluster, After that, everything seemed normal, I run the following command to see the description of the node

```
oc describe node node0-066an8.ocx.oqg  | egrep 'Capacity|Allocatable|gpu'
openshift.com/gpu-accelerator=true
Capacity:
 nvidia.com/gpu:  2
Allocatable:
 nvidia.com/gpu:  2
```

and then, My test pod could not be scheduled to the GPU node

```
  Warning  FailedScheduling  3s (x5 over 9s)  default-scheduler  0/6 nodes are available: 3 node(s) didn't match node selector, 6 Insufficient nvidia.com/gpu.
```

##### Here is some environment information to refer to

* This is my test pod

```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
  namespace: nvidia
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1"
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seLinuxOptions:
          type: nvidia_container_t

      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
```

* This is an excerpt from the description of node

```
Addresses:
  InternalIP:  10.10.12.250
  Hostname:    node0-066an8.ocx.oqg
Capacity:
 cpu:             8
 hugepages-1Gi:   0
 hugepages-2Mi:   0
 memory:          65770688Ki
 nvidia.com/gpu:  2
 pods:            250
Allocatable:
 cpu:             8
 hugepages-1Gi:   0
 hugepages-2Mi:   0
 memory:          65668288Ki
 nvidia.com/gpu:  2
 pods:            250
System Info:
 Machine ID:                 42024bb4774e42ef9b343e023a9ec6e6
 System UUID:                00000000-0000-0000-0000-4CCC6A46B4C2
 Boot ID:                    b7053c95-6a25-46af-819a-36f846e3b45e
 Kernel Version:             3.10.0-1160.45.1.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://20.10.11
 Kubelet Version:            v1.11.0+d4cacc0
 Kube-Proxy Version:         v1.11.0+d4cacc0
Non-terminated Pods:         (11 in total)
```

* This is the log of the Nvidia-device-plugin service

```
2021/12/07 12:28:58 Loading NVML
2021/12/07 12:28:58 Fetching devices.
2021/12/07 12:28:58 Starting FS watcher.
2021/12/07 12:28:58 Starting OS watcher.
2021/12/07 12:28:58 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2021/12/07 12:28:58 Registered device plugin with Kubelet
```

* This is the /etc/docker-daemon. json configuration

```
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
  "exec-opts": ["native.cgroupdriver=systemd"]
}
```

* This is a version of OpenShift

```
v3.11.0+62803d0-1
```

* I set DevicePlugins and Accelerators to true in feature-gates

* Yaml file for nvidia-device-plugin

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: nvidia-device-plugin-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: openshift.com/gpu-accelerator
                operator: Exists
      tolerations:
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - image: nvidia/k8s-device-plugin:1.11
        name: nvidia-device-plugin-ctr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seLinuxOptions:
            type: nvidia_container_t
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
```

* To verify correct operation of driver and container enablement

```
docker run --user 1000:1000 --security-opt=no-new-privileges --cap-drop=ALL  --security-opt label=type:nvidia_container_t  docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1

[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```
