### ISSUE TITLE
Enable resource renaming in time-slicing shared GPUs

### ISSUE THREAD

**Issue by Telemaco019** [NVIDIA/k8s-device-plugin#353]
### 1. Issue or feature description

I would like GPUs shared through time-slicing to be exposed as Kubernetes resources with a custom name (for instance `nvidia.com/gpu.shared` instead of `nvidia.com/gpu`). 

The configuration allows doing that through the field `rename`, as in the example below, but this feature has been disabled and the field is thus ignored. 

```yaml
version: v1
sharing:
  timeSlicing:
    resources:
    - name: nvidia.com/gpu
      rename: nvidia.com/gpu.shared
      replicas: 2
```

Will the "rename" feature be re-enabled any time soon? Are there any known side effects in enabling this feature for time-slicing shared GPUs?

**Comment by maltegrosse** [comment]
the parameter needs to be setup in the timeSlicing node (not the resources list):
```
version: v1
sharing:
  timeSlicing:
    renameByDefault: <bool>
```
