### ISSUE TITLE
Time-slicing config update: "Error: error creating symlink: file exists"

### ISSUE THREAD

**Issue by Telemaco019** [NVIDIA/k8s-device-plugin#364]
### 1. Issue or feature description
When changing between different time-slicing configurations by updating the label `nvidia.com/device-plugin.config` of a node (as explained in the [documentation](https://github.com/NVIDIA/k8s-device-plugin#shared-access-to-gpus-with-cuda-time-slicing)) the nvidia-device-plugin crashes with the following error:

```
│ config-manager time="2022-12-23T13:54:55Z" level=info msg="Waiting for change to 'nvidia.com/device-plugin.config' label"                                                                                                                │
│ config-manager time="2022-12-23T13:54:55Z" level=info msg="Label change detected: nvidia.com/device-plugin.config=config-3"                                                                                                              │
│ config-manager time="2022-12-23T13:54:55Z" level=info msg="Updating to config: config-3"                                                                                                                                                 │
│ config-manager time="2022-12-23T13:54:55Z" level=info msg="Error: error creating symlink: symlink /available-configs/config-3 /config/config.yaml: file exists"
```

This happens when the ConfigMap containing the available configurations is edited by removing the entry corresponding to the current configuration, and the node label `nvidia.com/device-plugin.config` is updated with another configuration name.

The issue is probably related to the Config Manager component trying to create the symlink to the new config file without properly deleting the existing symlink pointing to the previous (deleted) configuration file, thus resulting in the "file exists" error mentioned above. 

### 2. Steps to reproduce the issue

1. Create the ConfigMap "time-slicing-config" containing 3 different time-slicing configurations
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config
  namespace: gpu-operator
data:
  config-1: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 2
  config-2: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 4
  config-3: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 8
```

2. Apply the configuration "config-1" to the Node
```bash
kubectl label node <node-name> nvidia.com/device-plugin.config=config-1
```

3. Edit the ConfigMap "time-slicing-config" deleting the entry "config-1". This is the resulting ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config
  namespace: gpu-operator
data:
  config-2: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 4
  config-3: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 8
```

5. Apply the config "config-3" to the Node
```bash
kubectl label node <node-name> nvidia.com/device-plugin.config=config-3
```
