### ISSUE TITLE
cannot unmarshal string into Go struct field PluginCommandLineFlags.flags.plugin.deviceListStrategy of type []string

### ISSUE THREAD

**Issue by xuzimianxzm** [NVIDIA/k8s-device-plugin#410]
I think the follow configuration has a issue: the field deviceListStrategy is a array,but you provide a string. so this will be cause a issue when the init container of nvidia-device-plugin-ctr startting.

```sh
cat << EOF > /tmp/dp-example-config0.yaml
version: v1
flags:
  migStrategy: "none"
  failOnInitError: true
  nvidiaDriverRoot: "/"
  plugin:
    passDeviceSpecs: false
    deviceListStrategy: envvar
    deviceIDStrategy: uuid
EOF
```

**Comment by xuzimianxzm** [comment]
and, the another related issue is in the init container of gpu-feature-discovery-init, it requires the field of deviceListStrategy  is a string, not a array.

```sh
unable to load config: unable to finalize config: unable to parse config file: error parsing config file: unmarshal error: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field PluginCommandLineFlags.flags.plugin.deviceListStrategy of type string
```

**Comment by elezar** [comment]
Thanks @xuzimianxzm the `deviceListStrategy` config option was updated to be a string late in the Device Plugin's `v0.14.0` release cycle and it seems the changes were never propagated to `gpu-feature-discovery`. This explains the error you're seeing in your second comment.

It does also seem as if we didn't implement a custom unmarshaller for the `deviceListStrategy` when extending this in the device plugin.

cc @cdesiniotis

**Comment by elezar** [comment]
As a workaround, could you specify the `deviceListStrategy` using the `DEVICE_LIST_STRATEGY` envvar instead?

**Comment by ndacic** [comment]
@elezar what do you mean? I am facing same issue. Deploying it as a daemon set with Flux, not using helm. Should I create DEVICE_LIST_STRATEGY env variable for container, set its value to envvar and exclude         deviceListStrategy: "envvar" from config map

**Comment by alekc** [comment]
@ndacic this is how I solved it for me:

```
nodeSelector:
  nvidia.com/gpu.present: "true"
config:
  map:
    default: |-
      version: v1
      flags:
        migStrategy: "none"
        failOnInitError: true
        nvidiaDriverRoot: "/"
        plugin:
          passDeviceSpecs: false
          deviceListStrategy:
            - envvar
          deviceIDStrategy: uuid
      sharing:
        timeSlicing:
          renameByDefault: false
          resources:
          - name: nvidia.com/gpu
            replicas: 10
```

**Comment by elezar** [comment]
This issue should be addressed in the `v0.14.1` release.

@ndacic please let me know if bumping the version does not address your issue so that I can better document the workaround.

**Comment by PrakChandra** [comment]
@elezar 
I am using version `0.15.0`

I need to set replicas to 1 so that I can have full resource access of the GPU node.

My config looks like this 
```
      version: v1
      flags:
        migStrategy: none
      sharing:
        mps:
          default_active_thread_percentage: 10
          resources:
            - name: nvidia.com/gpu
              replicas: 2
```
So my g4dn.2xlarge instance gives 40 SM, but the pods are to have 20 SM with replicas set to 2.

When I do install version ```0.15.0``` I get the following error 
![image](https://github.com/NVIDIA/k8s-device-plugin/assets/95615399/24bae8ed-ab60-4098-be86-f0e03be8bf03)


Could you please suggest to me how and where I can configure this replica count as 1 so that I do not get the error

**Comment by klueska** [comment]
It's not clear what you hope to accomplish by enabling MPS but setting its replicas to 1. If we allowed you to set replicas to 1, then you would get an MPS server started for the GPU, but only be able to connect 1 workload/pod to it (i.e. no sharing would be possible).

Can you please elaborate on exactly what your expectations are for using MPS? It sounds like maybe time-slicing is more what you are looking for. Either that, or (as I suggested before), maybe you want a way to limit the memory of each workload, but allow them all to share the same compute.

Please clarify what your expectations are. Just saying you want a way to "set replicas to 1" doesn't tell us anything, because that is a disallowed configuration for the reason mentioned above.

**Comment by PrakChandra** [comment]
@klueska 

I provisioned an Optimised EKS GPU node g4dn.2xlarge with 1 GPU, configuration as follows

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/95615399/453d945e-6d9a-407a-920b-f314b9c4bb06)


In order to have my workloads/pods get scheduled over it, I created the daemonset via helm 
```helm upgrade -i nvdp nvdp/nvidia-device-plugin     --version=0.15.0     --namespace kube-system     -f values.yaml```

Output:

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/95615399/6a08eae8-8fb3-4245-9671-fd88b2d78440)

Logs:

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/95615399/1f7046b1-9c28-463d-856c-0ca7c751da6a)


My Config file is like this and I have updated this in the values.yaml file in order to get MPS sharing so that multiple workloads can be scheduled on the GPU node
```
  map: 
    default: |-
      version: v1
      flags:
        migStrategy: none
      sharing:
        mps:
          resources:
            - name: nvidia.com/gpu
              replicas: 2
```
===========================================================================

Issue:
-------
When I set `replicas: 2` I get the following output. This output is from one of the pods which is getting scheduled on the GPU node

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/95615399/7e791f78-cb8e-4b3a-ab73-ab58ab1096c5)

In the above output, the multiprocessor count is 20, however, I need multiprocessor count as 40 so that the workloads can perform efficiently, otherwise with 20 it gets slow.

My expectation:
----------------
If I can set the `replicas: 1` , then the multiprocessor count would become 40 and the workloads can do the procseesing efficiently.

I followed this doc and came to this expectation:

Ref: https://github.com/NVIDIA/k8s-device-plugin/tree/release-0.15

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/95615399/ae277d57-2689-48d5-a8cd-2e287cf409f1)
