### ISSUE TITLE
 Enhance Nvidia Device plugin support CUDA 9

### ISSUE THREAD

**Issue by bleachzk** [NVIDIA/k8s-device-plugin#46]

**Comment by flx42** [comment]
Can you be more specific? You can run CUDA 9.0 containers with the device plugin today.

**Comment by openthings** [comment]
I run Titan V with Cuda9.1 get errors:

> gpu-cuda
openthings
等待中：CrashLoopBackOff
1
3 分钟
 0
 1.164 Mi
0/1 nodes are available: 1 Insufficient nvidia.com/gpu.
Back-off restarting failed container

The pod yaml as following:
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-cuda
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
```

but run nvidia/digits will success, the pod yaml as:
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-digits
spec:
  containers:
    - name: digits-container
      image: nvidia/digits:6.0
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
```
why ?
