### ISSUE TITLE
can't schedule GPU pod

### ISSUE THREAD

**Issue by miramar-labs** [NVIDIA/k8s-device-plugin#49]
I'm running K8s 1.10.2-0 on RHEL7.4 with docker 18.03.1
I have a 9 worker node K8s cluster. Only one of those nodes has a GPU on it (NVIDIA TitanXp).
I installed nvidia-docker2 on ALL worker nodes:
`nvidia-docker2.noarch                  2.0.3-1.docker18.03.1.ce`
I installed nvidia-container-runtime on ALL worker nodes:
`nvidia-container-runtime.x86_64        2.0.0-1.docker18.03.1`
I installed nvidia-device-plugin.yml v1.10 via kubectl (the device plugin is running OK on all worker nodes)

I can ssh into my GPU worker node and run nvidia-smi inside a container OK:

```
[whacuser@gpu ~]$ sudo docker run --rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from nvidia/cuda
297061f60c36: Pull complete
e9ccef17b516: Pull complete
dbc33716854d: Pull complete
8fe36b178d25: Pull complete
686596545a94: Pull complete
f611dfbee954: Pull complete
c51814f3e9ba: Pull complete
5da0fc07e73a: Pull complete
97462b1887aa: Pull complete
924ea239f6fe: Pull complete
Digest: sha256:69f3780f80a72cb7cebc7f401a716370f79412c5aa9362306005ca4eb84d0f3c
Status: Downloaded newer image for nvidia/cuda:latest
Mon May 14 20:14:16 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.25                 Driver Version: 390.25                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:13:00.0 Off |                  N/A |
| 23%   21C    P8     8W / 250W |      0MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
I label my GPU worker node like so: 
`kubectl label nodes gpu accelerator=nvidia-titan-xp --overwrite=true`

However, when I try to run a pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
    - name: digits-container
      image: nvidia/digits:6.0
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  nodeSelector:
    accelerator: nvidia-titan-xp
```

I get an error:

**0/12 nodes are available: 11 MatchNodeSelector, 12 Insufficient nvidia.com/gpu, 3 PodToleratesNodeTaints.**

any ideas?
