### ISSUE TITLE
an amazon machine image (AMI) that meets the prequites of k8s-device-plugin

### ISSUE THREAD

**Issue by BBerabi** [NVIDIA/k8s-device-plugin#494]
I am looking for a public Amazon Machine Image (AMI) that already meets all the requirements mentioned in README. I basically need an image on which I can apply the device plugins daemon set directly without doing anything. 

Does anyone know such an image or a similar solution?

**Comment by ArangoGutierrez** [comment]
Hey @BBerabi , there is no official image that meets your needed requirement. But we have a new *experimental* tool that could take you there in a few quick steps .

- https://github.com/NVIDIA/holodeck


What you are looking for would look like:

```yaml
apiVersion: holodeck.nvidia.com/v1alpha1
kind: Environment
metadata:
  name: holodeck
  description: "Devel infra environment"
spec:
  provider: aws # or ssh currently supported
  auth:
    keyName: user
    privateKey: "/Users/user/.ssh/user.pem"
  instance: # if provider is ssh you need to define here the hostUrl
    type: g4dn.xlarge # A small GPU instance type
    region: eu-north-1
    ingressIpRanges:
      - 192.168.1.0/26 # The Ip range to enable on the SecurityGroup
    image:
      architecture: amd64
      imageId: ami-0fe8bec493a81c7da # Ubuntu 22.04 image
  nvContainerToolKit:
    install: true
  kubernetes:
    install: true
    installer: kubeadm # supported installers: kubeadm, kind, microk8s
    version: v1.28.5
```

Again is a tool underdevelopment, but it can take you to an AWS EC2 ready instance, to just deploy the `k8s-device-plugin` and get to work
