### ISSUE TITLE
Using CUDA MPS to enable GPU sharing, the pod occupies all GPU memory.

### ISSUE THREAD

**Issue by ysz-github** [NVIDIA/k8s-device-plugin#569]
I have already enabled GPU sharing using CUDA MPS, but when deploying pods with yaml, it occupies all GPU memory. Is my way of requesting GPU resources wrong?

The way I request GPU resources is as follows:
resources:
  limits:
    nvidia.com.gpu: 1

**Comment by klueska** [comment]
How did you set up MPS?

**Comment by ysz-github** [comment]
> 您是如何设置 MPS 的？

I haven't set MPS in the YAML, just applied for GPU resources like in Time-slicing mode. How should I set it up? Thank you!

**Comment by ysz-github** [comment]
> How did you set up MPS?

The settings to enable CUDA MPS are as follows:

```yaml
version: v1
flags:
  migStrategy: "none"
  failOnInitError: true
  nvidiaDriverRoot: "/"
  plugin:
    passDeviceSpecs: false
    deviceListStrategy: "envvar"
    deviceIDStrategy: "uuid"
  gfd:
    oneshot: false
    noTimestamp: false
    outputFile: /etc/kubernetes/node-feature-discovery/features.d/gfd
    sleepInterval: 60s
sharing:
  mps:
    resources:
    - name: nvidia.com/gpu
      replicas: 10
```
