### ISSUE TITLE
When GPU is MIG mixed model, one pod use two MIG Instance, use nvidia-smi can't find.

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/k8s-device-plugin#728]
I having follow the deployment resources, set `nvidia.com/mig-1g.10gb` and `nvidia.com/mig-1g.20gb` as two resources, and node having exist this mig resources.
```yaml
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
        nvidia.com/mig-1g.10gb: "1"
        nvidia.com/mig-1g.20gb: "2"
```

use `nvidia-smi` only find a `nvidia.com/mig-1g.10gb` mig instances, can't find `nvidia.com/mig-1g.20gb`.

We found because kubelet cannot handle the same environment variables, Is this by design or is it an implementation bug?
![image](https://github.com/NVIDIA/k8s-device-plugin/assets/15009201/cb081f22-1e4d-4332-a6a1-ace7617dfaf8)

https://github.com/kubernetes/kubernetes/blob/4bb434501d9ee5edda6faf52a9d6d32a969ae183/pkg/kubelet/cm/devicemanager/pod_devices.go#L264-L274
