### ISSUE TITLE
feature discovery worker pods scheduled on wrong nodes

### ISSUE THREAD

**Issue by garymm** [NVIDIA/k8s-device-plugin#734]
Hi,
I've deployed via the nvidia-device-plugin Helm chart version `0.14.5`.
I've got 3 daemon sets:
* nvidia-device-plugin
* nvidia-device-plugin-gpu-feature-discovery
* nvidia-device-plugin-gpu-feature-discovery-worker

The first two create pods on all the nodes that have the label `nvidia.com/gpu.present: "true"`
The third one does *not* create pods on those nodes (but it does create pods on nodes that don't have GPUs).
Looking at the YAML it does appear that the first two DaemonSets have a ndoeAffinity specified, while the worker does not. See below.
The lack of nodeAffinity explains why it does create pods on the non-GPU nodes. This seems like a bug, but it's not a big deal.
However the real issue is that it does not create pods on GPU nodes. I'm really not sure why. Maybe the difference is in tolerations?

Thanks for any advice!

The non-worker tolerations:
```yaml
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
```

The worker tolerations:
```yaml
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Equal
          value: present
```          

Worker labels:
```yaml
    app.kubernetes.io/instance: nvidia-device-plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.12.1
    helm.sh/chart: nfd-0.12.1
    role: worker
```

This is what's set on the nvidia-device-plugin-gpu-feature-discovery:
```yaml
spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: feature.node.kubernetes.io/pci-10de.present
                  operator: In
                  values:
                  - "true"
              - matchExpressions:
                - key: feature.node.kubernetes.io/cpu-model.vendor_id
                  operator: In
                  values:
                  - NVIDIA
              - matchExpressions:
                - key: nvidia.com/gpu.present
                  operator: In
                  values:
                  - "true"
```
